version: '3.8'

services:

  backend:
    #api-movie:1.0
    image: 122418/api-movie:1.0
    container_name: api-movie
    ports:
      - "8080:8080"
    environment:
      - API_URL=jdbc:postgresql://db:5432/moviedb_1
      - API_USER=postgres
      - API_PASSWORD=postgres
    links:
      - db
        
  db:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moviedb_1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"